parameters:
    notifications:
        email:
          aws_ses:
            name: aws_ses
            retries: 3
          mailgun:
            name: mailgun
            retries: 3

        sms:
          twilio:
            name: twilio
            retries: 3

        push:
          pushy:
            name: pushy
            retries: 3
