# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

imports:
    - { resource: 'notifications.yaml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\NotificationPublisher\Infrastructure\Notification\TypeProviderFactory:
        arguments:
            $factories:
                - '@App\NotificationPublisher\Infrastructure\Notification\Email\ProviderFactory'
                - '@App\NotificationPublisher\Infrastructure\Notification\Sms\ProviderFactory'
                - '@App\NotificationPublisher\Infrastructure\Notification\Push\ProviderFactory'
                

    App\NotificationPublisher\Infrastructure\Notification\Email\ProviderFactory:
        arguments:
            $providers:
                - '@App\NotificationPublisher\Infrastructure\Notification\Email\Provider\AwsSesEmailProvider'
                - '@App\NotificationPublisher\Infrastructure\Notification\Email\Provider\MailgunEmailProvider'

    App\NotificationPublisher\Infrastructure\Notification\Sms\ProviderFactory:
        arguments:
            $providers:
                - '@App\NotificationPublisher\Infrastructure\Notification\Sms\Provider\TwilioSmsProvider'

    App\NotificationPublisher\Infrastructure\Notification\Push\ProviderFactory:
        arguments:
            $providers:
                - '@App\NotificationPublisher\Infrastructure\Notification\Push\Provider\PushyPushProvider'
    
    
    App\NotificationPublisher\Infrastructure\Notification\TypeProviderStrategyBuilder:
        arguments:
            $strategies:
                - '@App\NotificationPublisher\Infrastructure\Notification\Email\ProviderStrategy'
                - '@App\NotificationPublisher\Infrastructure\Notification\Sms\ProviderStrategy'
                - '@App\NotificationPublisher\Infrastructure\Notification\Push\ProviderStrategy'

    App\NotificationPublisher\Infrastructure\Notification\Email\ProviderStrategy:
        arguments:
            $config: '%notifications%'

    App\NotificationPublisher\Infrastructure\Notification\Sms\ProviderStrategy:
        arguments:
            $config: '%notifications%'

    App\NotificationPublisher\Infrastructure\Notification\Push\ProviderStrategy:
        arguments:
            $config: '%notifications%'
